imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @DashboardBundle/Resources/config/dashboard.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            #StofDoctrineExtensionsBundle: ~
            #DashboardBundle: ~
            ApplicationSonataUserBundle: ~
            SonataUserBundle: ~
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true        

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
    #    group_manager: sonata.user.orm.group_manager        
    #service:
    #    user_manager: sonata.user.orm.user_manager

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:            
            tree: true
            softdeleteable: true
            timestampable: false
            sluggable: false     

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
#Sonata Configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.block.service.newsletter: ~
        
        sonata.block.service.text: ~
        sonata.user.block.account: ~
        sonata.user.block.menu: ~
        
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin_doctrine_orm.block.audit:
            contexts:   [admin]
            
        #sonata.block.service.action:
        #sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:
sonata_admin:
    title: Админка
    #title_logo: bundles/acmedemo/img/fancy_acme_logo.png   
    templates:
        # default layout used at the dashboard
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
        
        #base layout used by the dashboard and an admin class
        layout:  SonataAdminBundle::standard_layout.html.twig
        #default layout used when an ajax request is performed
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        
        #the template to use for the list action
        list:    SonataAdminBundle:CRUD:list.html.twig
        #the template to use for the show action
        show:    SonataAdminBundle:CRUD:show.html.twig
        #the template to use for the edit and create action
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        #the template to use for the history / audit action
        history: SonataAdminBundle:CRUD:history.html.twig
        #the template to use for previewing an edit / create action
        preview: SonataAdminBundle:CRUD:preview.html.twig
        #the template to use for the delete action
        delete:  SonataAdminBundle:CRUD:delete.html.twig
        batch:   SonataAdminBundle:CRUD:list__batch.html.twig
        batch_confirmation: SonataAdminBundle:CRUD:batch_confirmation.html.twig
        
        #used to represent the entity in one-to-one/many-to-one relations
        short_object_description: SonataAdminBundle:Helper:short-object-description.html.twig        
        #the template used for the list of admin blocks on the dashboard
        list_block: SonataAdminBundle:Block:block_admin_list.html.twig
         
    dashboard:        
        blocks:
                #settings: {groups: [user, sign] } 
            #- { position: left, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata.block.service.newsletter}
            - { position: right, type: sonata.block.service.newsletter}
            - { position: center, type: sonata.block.service.text, settings: { content: "<h2>Text Block</h2> <p>This is a <code>sonata.block.service.text</code> from the Block Bundle, you can create and add new block in these area by configuring the <code>sonata_admin</code> section.</p>"} }        
        groups:
            user:                
                #label_catalogue: ???
                #item_adds: ???
                #roles: [ SUPER_ADMIN ]
                label: Пользователи
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - sonata.admin.Department
            sign:
                label: Приметы
                items:
                    - sonata.admin.SignPlace
                    - sonata.admin.SignType
            car:
                label: Авто
                items:
                    - sonata.admin.CarColor
            identification:
                label: Отождествление
                items:
                    - sonata.admin.IdentificationCategory
                    - sonata.admin.IdentificationType
                    - sonata.admin.IdentificationReason
            directory:
                label: Справочники
                items:
                    - sonata.admin.Category
                    - sonata.admin.ConnectionType
                    - sonata.admin.Sex
                    - sonata.admin.Height
                    - sonata.admin.SimilarTo
                    - sonata.admin.Physique
                    - sonata.admin.Nationality
sonata_user:  
    security_acl:     false
    class:
        user:         Application\Sonata\UserBundle\Entity\User
        group:        Application\Sonata\UserBundle\Entity\Group
    profile:
        form:
            type:               sonata_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]
        # Profile show page is a dashboard as in SonataAdminBundle
        dashboard:
            blocks:
                - { position: left, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> This is a sample user profile dashboard, feel free to override it in the configuration! Want to make this text dynamic? For instance display the user's name? Create a dedicated block and edit the configuration!"} }
                #- { position: left, type: sonata.order.block.recent_orders, settings: { title: Recent Orders, number: 5, mode: public }}
                #- { position: right, type: sonata.timeline.block.timeline, settings: { max_per_page: 15 }}
                #- { position: right, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 5, mode: public }}
                #- { position: right, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 5, mode: public }}
        # Customize user portal menu by setting links
        menu:
            - { route: 'sonata_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            #- { route: 'sonata_customer_addresses', label: 'link_list_addresses', domain: 'SonataCustomerBundle'}
            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}
            #- { route: 'sonata_order_index', label: 'order_list', domain: 'SonataOrderBundle'}