security:
    #role_hierarchy:
    #    ROLE_ADMIN: ROLE_USER
        
    encoders:
        Application\DashboardBundle\Entity\User:
            algorithm: md5
            encode-as-base64: false
            iterations: 1
            
    providers:
        main:
            entity: { class: DashboardBundle:User, property: login }

    firewalls:
        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /
            logout: true
            security: true
            anonymous: true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: /admin/.*, role: ROLE_ADMIN }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
